global.errorCodes = {
  NO_TOKEN: 1,
  DISABLED_USER: 2,
  INVALID_TOKEN: 3,
  USER_EXISTS: 4,
  USER_DATA_LOST: 5,
  STAFF_DATA_LOST: 6,
  INCORRECT_USERNAME_PASSWORD: 7,
  UNKNOWN_ERROR: 8,
  NOT_AUTHORIZED_ADD: 9,
  NOT_AUTHORIZED_Edit: 10,
  NOT_AUTHORIZED_DELETE: 11,
  NOT_AUTHORIZED_VIEW: 12,
  INCORRECT_IMAGE_TYPE: 13,
  NO_USER_ID: 14,
  NO_FEATURE_ID: 15,
  INCORRECT_IMAGE_TYPE: 16,
  NO_IMAGES_UPLOADED: 17,
  NO_POLICY_ID: 18,
  NO_STADIUM_ID: 19,
  TIME_ALREADY_RESERVED: 20,
  TIME_IS_DISABLED: 21,
  NO_RESERVATION_ID: 22,
  STADIUM_IS_FAVORITE: 23,
  STADIUM_IS_BOT_FAVORITE: 24,
  INCORRECT_PASSWORD: 25,
  NO_PLAYER_TRANSACTION_ID: 26,
  NO_OWNER_TRANSACTION_ID: 27,
  MISSING_STADIUM_ID: 28,
  NOT_STADIUM_OWNER: 29,
  INCORRECT_STADIUM_ID: 30,
  MISSING_RESERVATION_ID: 31,
  CANNOT_CANCEL_RESERVATION: 32,
  NO_METADATA_KEY: 33,
  METADATA_EXISTS: 34,
  INVALID_INPUT: 35,
  NO_RESERVATION_MESSAGE_ID: 36,
  EMAIL_TOKEN_EXPIRED: 37,
  EMAIL_ALREADY_VERIFIED: 38,
  EMAIL_NOT_VERIFIED: 39,
  EMAIL_NOT_REGISTERED: 40,
};

const errorMessages = {
  "1_en": "Access denied, no token provided",
  "1_ar": "ممنوع الاستخدام, لم يتم ارسال التوكن",
  "2_en": "This account is disabled",
  "2_ar": "هذا الحساب مغلق",
  "3_en": "Invalid token",
  "3_ar": "هذا التوكن غير صحيح",
  "4_en": "User already exists",
  "4_ar": "هذا الحساب موجود بالفعل",
  "5_en": "User data doesn't exist, please register again",
  "5_ar": "بيانات الحساب غير موجوده, يجب التسجيل مره اخري",
  "6_en": "staff data doesn't exist, contact admin",
  "6_ar": "بيانات الحساب غير موجوده, قم بالتواصل مع مدير النظام",
  "7_en": "Incorrect phone number or password",
  "7_ar": "رقم الموبايل او كلمه المرور غير صحيح",
  "8_en": "An unknown error occurred",
  "8_ar": "مشكله غير معروفه",
  "9_en": "You are not allowed to add to this category",
  "9_ar": "غير مسموح لك باضافه هذا المحتوي",
  "10_en":
    "You are not allowed to edit one or more of the information that you provided",
  "10_ar": "غير مسموح لك بتغير هذا المحتوي",
  "11_en": "You are not allowed to delete from this category",
  "11_ar": "غير مسموح لك بالغاء هذا المحتوي",
  "12_en":
    "You are not allowed to view one or more of the information of this category",
  "12_ar": "غير مسموح لك بالاتطلاع علي هذا المحتوي",
  "13_en": "uploaded file must be jpeg or png",
  "13_ar": "يجب ان يكون الملف من نوع jpeg او png",
  "14_en": "No user exist for this id",
  "14_ar": "لا يوجد مستخدم بهذا الرقم",
  "15_en": "No feature exist for this id",
  "15_ar": "لا توجد ميذه بهذا الرقم",
  "16_en": "uploaded file must be jpeg or png",
  "16_ar": "يجب ان يكون الملف من نوع jpeg او png",
  "17_en": "No image/images were uploaded",
  "17_ar": "لم يتم رفع اي صور",
  "18_en": "No policy exist for this id",
  "18_ar": "لا توجد سياسه بهذا الرقم",
  "19_en": "No Stadium exist for this id",
  "19_ar": "لا يوجد ملعب بهذا الرقم",
  "20_en": "This time slot has already been reserved",
  "20_ar": "لقد تم حجز هذا الوقت بالفعل",
  "21_en": "This time slot is disabled by admin",
  "21_ar": "قام صاحب الملعب باغلاق هذا الوقت",
  "22_en": "No reservation exist for this id",
  "22_ar": "لا توجد حجز بهذا الرقم",
  "23_en": "This stadium is already this user's favorite",
  "23_ar": "هذا الملعب مفضل بالفعل",
  "24_en": "This stadium is not this user's favorite",
  "24_ar": "هذا الملعب ليس من الملاعب المفضله",
  "25_en": "The old password is incorrect",
  "25_ar": "كلمه المرور القديمه غير صحيحه",
  "26_en": "No player transaction exist for this id",
  "26_ar": "لا توجد عمليه بهذا الرقم",
  "27_en": "No owner transaction exist for this id",
  "27_ar": "لا توجد عمليه بهذا الرقم",
  "28_en": "Stadium id is missing",
  "28_ar": "رقم الملعب غير موجود",
  "29_en": "You are not the owner of this stadium",
  "29_ar": "ان لست مالك هذا الملعب",
  "30_en": "Incorrect stadium id",
  "30_ar": "رقم تعريف الاستاد غير صحيح",
  "31_en": "Reservation id is missing or invalid",
  "31_ar": "بيانات الحجز غير صحيحه",
  "32_en": "You can't cancel this reservation",
  "32_ar": "لا يمكنك الغاء هذا الحجز",
  "33_en": "No metadata exist for this key",
  "33_ar": "لا توجد بيانات بهذا المفتاح",
  "34_en": "Metadata already exists",
  "34_ar": "هذه البيانات موجود بالفعل",
  "35_en": "This input is invalid",
  "35_ar": "هذه المدخلات غير صحيحه",
  "36_en": "No message exist for this key",
  "36_ar": "لا توجد رساله بهذا المفتاح",
  "37_en": "This token has expired",
  "37_ar": "هذا الرمز منتهي الصلاحيه",
  "38_en": "This email is already verified",
  "38_ar": "هذا البريد الالكتروني ماكد",
  "39_en": "This email is not verified",
  "39_ar": "هذا البريد الالكتروني غير ماكد",
  "40_en": "This email is not registered",
  "40_ar": "هذا البريد الالكتروني غير مسجل",
};

module.exports.getErrorObject = async (errorCode, languageCode) => {
  const errorObject = {
    error_code: errorCode,
    error_message: await this.getErrorMessageByErrorCode(
      errorCode,
      languageCode
    ),
  };

  return errorObject;
};

module.exports.getErrorMessageByErrorCode = async (errorCode, languageCode) => {
  return errorMessages[String(errorCode) + "_" + String(languageCode)];
};
